import { useMemo } from 'react';
import { Dropdown, DropdownItemProps, DropdownProps } from 'semantic-ui-react';
import i18n from 'translations/i18n';

const countryOptions: DropdownItemProps[] = [
  { text: 'Afghanistan', flag: 'af', value: 'af', key: 'af' },
  { text: 'Aland Islands', flag: 'ax', value: 'ax', key: 'ax' },
  { text: 'Albania', flag: 'al', value: 'al', key: 'al' },
  { text: 'Algeria', flag: 'dz', value: 'dz', key: 'dz' },
  { text: 'American Samoa', flag: 'as', value: 'as', key: 'as' },
  { text: 'Andorra', flag: 'ad', value: 'ad', key: 'ad' },
  { text: 'Angola', flag: 'ao', value: 'ao', key: 'ao' },
  { text: 'Anguilla', flag: 'ai', value: 'ai', key: 'ai' },
  { text: 'Antigua', flag: 'ag', value: 'ag', key: 'ag' },
  { text: 'Argentina', flag: 'ar', value: 'ar', key: 'ar' },
  { text: 'Armenia', flag: 'am', value: 'am', key: 'am' },
  { text: 'Aruba', flag: 'aw', value: 'aw', key: 'aw' },
  { text: 'Australia', flag: 'au', value: 'au', key: 'au' },
  { text: 'Austria', flag: 'at', value: 'at', key: 'at' },
  { text: 'Azerbaijan', flag: 'az', value: 'az', key: 'az' },
  { text: 'Bahamas', flag: 'bs', value: 'bs', key: 'bs' },
  { text: 'Bahrain', flag: 'bh', value: 'bh', key: 'bh' },
  { text: 'Bangladesh', flag: 'bd', value: 'bd', key: 'bd' },
  { text: 'Barbados', flag: 'bb', value: 'bb', key: 'bb' },
  { text: 'Belarus', flag: 'by', value: 'by', key: 'by' },
  { text: 'Belgium', flag: 'be', value: 'be', key: 'be' },
  { text: 'Belize', flag: 'bz', value: 'bz', key: 'bz' },
  { text: 'Benin', flag: 'bj', value: 'bj', key: 'bj' },
  { text: 'Bermuda', flag: 'bm', value: 'bm', key: 'bm' },
  { text: 'Bhutan', flag: 'bt', value: 'bt', key: 'bt' },
  { text: 'Bolivia', flag: 'bo', value: 'bo', key: 'bo' },
  { text: 'Bosnia', flag: 'ba', value: 'ba', key: 'ba' },
  { text: 'Botswana', flag: 'bw', value: 'bw', key: 'bw' },
  { text: 'Bouvet Island', flag: 'bv', value: 'bv', key: 'bv' },
  { text: 'Brazil', flag: 'br', value: 'br', key: 'br' },
  { text: 'British Virgin Islands', flag: 'vg', value: 'vg', key: 'vg' },
  { text: 'Brunei', flag: 'bn', value: 'bn', key: 'bn' },
  { text: 'Bulgaria', flag: 'bg', value: 'bg', key: 'bg' },
  { text: 'Burkina Faso', flag: 'bf', value: 'bf', key: 'bf' },
  { text: 'Burma', flag: 'mm', value: 'mm', key: 'mm' },
  { text: 'Burundi', flag: 'bi', value: 'bi', key: 'bi' },
  { text: 'Caicos Islands', flag: 'tc', value: 'tc', key: 'tc' },
  { text: 'Cambodia', flag: 'kh', value: 'kh', key: 'kh' },
  { text: 'Cameroon', flag: 'cm', value: 'cm', key: 'cm' },
  { text: 'Canada', flag: 'ca', value: 'ca', key: 'ca' },
  { text: 'Cape Verde', flag: 'cv', value: 'cv', key: 'cv' },
  { text: 'Cayman Islands', flag: 'ky', value: 'ky', key: 'ky' },
  { text: 'Central African Republic', flag: 'cf', value: 'cf', key: 'cf' },
  { text: 'Chad', flag: 'td', value: 'td', key: 'td' },
  { text: 'Chile', flag: 'cl', value: 'cl', key: 'cl' },
  { text: 'China', flag: 'cn', value: 'cn', key: 'cn' },
  { text: 'Christmas Island', flag: 'cx', value: 'cx', key: 'cx' },
  { text: 'Cocos Islands', flag: 'cc', value: 'cc', key: 'cc' },
  { text: 'Colombia', flag: 'co', value: 'co', key: 'co' },
  { text: 'Comoros', flag: 'km', value: 'km', key: 'km' },
  { text: 'Congo', flag: 'cd', value: 'cd', key: 'cd' },
  { text: 'Congo Brazzaville', flag: 'cg', value: 'cg', key: 'cg' },
  { text: 'Cook Islands', flag: 'ck', value: 'ck', key: 'ck' },
  { text: 'Costa Rica', flag: 'cr', value: 'cr', key: 'cr' },
  { text: 'Cote Divoire', flag: 'ci', value: 'ci', key: 'ci' },
  { text: 'Croatia', flag: 'hr', value: 'hr', key: 'hr' },
  { text: 'Cuba', flag: 'cu', value: 'cu', key: 'cu' },
  { text: 'Cyprus', flag: 'cy', value: 'cy', key: 'cy' },
  { text: 'Czech Republic', flag: 'cz', value: 'cz', key: 'cz' },
  { text: 'Denmark', flag: 'dk', value: 'dk', key: 'dk' },
  { text: 'Djibouti', flag: 'dj', value: 'dj', key: 'dj' },
  { text: 'Dominica', flag: 'dm', value: 'dm', key: 'dm' },
  { text: 'Dominican Republic', flag: 'do', value: 'do', key: 'do' },
  { text: 'Ecuador', flag: 'ec', value: 'ec', key: 'ec' },
  { text: 'Egypt', flag: 'eg', value: 'eg', key: 'eg' },
  { text: 'El Salvador', flag: 'sv', value: 'sv', key: 'sv' },
  { text: 'England', flag: 'gb eng', value: 'en', key: 'en' },
  { text: 'Equatorial Guinea', flag: 'gq', value: 'gq', key: 'gq' },
  { text: 'Eritrea', flag: 'er', value: 'er', key: 'er' },
  { text: 'Estonia', flag: 'ee', value: 'ee', key: 'ee' },
  { text: 'Ethiopia', flag: 'et', value: 'et', key: 'et' },
  { text: 'Europeanunion', flag: 'eu', value: 'eu', key: 'eu' },
  { text: 'Falkland Islands', flag: 'fk', value: 'fk', key: 'fk' },
  { text: 'Faroe Islands', flag: 'fo', value: 'fo', key: 'fo' },
  { text: 'Fiji', flag: 'fj', value: 'fj', key: 'fj' },
  { text: 'Finland', flag: 'fi', value: 'fi', key: 'fi' },
  { text: 'France', flag: 'fr', value: 'fr', key: 'fr' },
  { text: 'French Guiana', flag: 'gf', value: 'gf', key: 'gf' },
  { text: 'French Polynesia', flag: 'pf', value: 'pf', key: 'pf' },
  { text: 'French Territories', flag: 'tf', value: 'tf', key: 'tf' },
  { text: 'Gabon', flag: 'ga', value: 'ga', key: 'ga' },
  { text: 'Gambia', flag: 'gm', value: 'gm', key: 'gm' },
  { text: 'Georgia', flag: 'ge', value: 'ge', key: 'ge' },
  { text: 'Germany', flag: 'de', value: 'de', key: 'de' },
  { text: 'Ghana', flag: 'gh', value: 'gh', key: 'gh' },
  { text: 'Gibraltar', flag: 'gi', value: 'gi', key: 'gi' },
  { text: 'Greece', flag: 'gr', value: 'gr', key: 'gr' },
  { text: 'Greenland', flag: 'gl', value: 'gl', key: 'gl' },
  { text: 'Grenada', flag: 'gd', value: 'gd', key: 'gd' },
  { text: 'Guadeloupe', flag: 'gp', value: 'gp', key: 'gp' },
  { text: 'Guam', flag: 'gu', value: 'gu', key: 'gu' },
  { text: 'Guatemala', flag: 'gt', value: 'gt', key: 'gt' },
  { text: 'Guinea', flag: 'gn', value: 'gn', key: 'gn' },
  { text: 'Guinea-Bissau', flag: 'gw', value: 'gw', key: 'gw' },
  { text: 'Guyana', flag: 'gy', value: 'gy', key: 'gy' },
  { text: 'Haiti', flag: 'ht', value: 'ht', key: 'ht' },
  { text: 'Heard Island', flag: 'hm', value: 'hm', key: 'hm' },
  { text: 'Honduras', flag: 'hn', value: 'hn', key: 'hn' },
  { text: 'Hong Kong', flag: 'hk', value: 'hk', key: 'hk' },
  { text: 'Hungary', flag: 'hu', value: 'hu', key: 'hu' },
  { text: 'Iceland', flag: 'is', value: 'is', key: 'is' },
  { text: 'India', flag: 'in', value: 'in', key: 'in' },
  { text: 'Indian Ocean Territory', flag: 'io', value: 'io', key: 'io' },
  { text: 'Indonesia', flag: 'id', value: 'id', key: 'id' },
  { text: 'Iran', flag: 'ir', value: 'ir', key: 'ir' },
  { text: 'Iraq', flag: 'iq', value: 'iq', key: 'iq' },
  { text: 'Ireland', flag: 'ie', value: 'ie', key: 'ie' },
  { text: 'Israel', flag: 'il', value: 'il', key: 'il' },
  { text: 'Italy', flag: 'it', value: 'it', key: 'it' },
  { text: 'Jamaica', flag: 'jm', value: 'jm', key: 'jm' },
  { text: 'Jan Mayen', flag: 'sj', value: 'sj', key: 'sj' },
  { text: 'Japan', flag: 'jp', value: 'jp', key: 'jp' },
  { text: 'Jordan', flag: 'jo', value: 'jo', key: 'jo' },
  { text: 'Kazakhstan', flag: 'kz', value: 'kz', key: 'kz' },
  { text: 'Kenya', flag: 'ke', value: 'ke', key: 'ke' },
  { text: 'Kiribati', flag: 'ki', value: 'ki', key: 'ki' },
  { text: 'Kuwait', flag: 'kw', value: 'kw', key: 'kw' },
  { text: 'Kyrgyzstan', flag: 'kg', value: 'kg', key: 'kg' },
  { text: 'Laos', flag: 'la', value: 'la', key: 'la' },
  { text: 'Latvia', flag: 'lv', value: 'lv', key: 'lv' },
  { text: 'Lebanon', flag: 'lb', value: 'lb', key: 'lb' },
  { text: 'Lesotho', flag: 'ls', value: 'ls', key: 'ls' },
  { text: 'Liberia', flag: 'lr', value: 'lr', key: 'lr' },
  { text: 'Libya', flag: 'ly', value: 'ly', key: 'ly' },
  { text: 'Liechtenstein', flag: 'li', value: 'li', key: 'li' },
  { text: 'Lithuania', flag: 'lt', value: 'lt', key: 'lt' },
  { text: 'Luxembourg', flag: 'lu', value: 'lu', key: 'lu' },
  { text: 'Macau', flag: 'mo', value: 'mo', key: 'mo' },
  { text: 'Macedonia', flag: 'mk', value: 'mk', key: 'mk' },
  { text: 'Madagascar', flag: 'mg', value: 'mg', key: 'mg' },
  { text: 'Malawi', flag: 'mw', value: 'mw', key: 'mw' },
  { text: 'Malaysia', flag: 'my', value: 'my', key: 'my' },
  { text: 'Maldives', flag: 'mv', value: 'mv', key: 'mv' },
  { text: 'Mali', flag: 'ml', value: 'ml', key: 'ml' },
  { text: 'Malta', flag: 'mt', value: 'mt', key: 'mt' },
  { text: 'Marshall Islands', flag: 'mh', value: 'mh', key: 'mh' },
  { text: 'Martinique', flag: 'mq', value: 'mq', key: 'mq' },
  { text: 'Mauritania', flag: 'mr', value: 'mr', key: 'mr' },
  { text: 'Mauritius', flag: 'mu', value: 'mu', key: 'mu' },
  { text: 'Mayotte', flag: 'yt', value: 'yt', key: 'yt' },
  { text: 'Mexico', flag: 'mx', value: 'mx', key: 'mx' },
  { text: 'Micronesia', flag: 'fm', value: 'fm', key: 'fm' },
  { text: 'Moldova', flag: 'md', value: 'md', key: 'md' },
  { text: 'Monaco', flag: 'mc', value: 'mc', key: 'mc' },
  { text: 'Mongolia', flag: 'mn', value: 'mn', key: 'mn' },
  { text: 'Montenegro', flag: 'me', value: 'me', key: 'me' },
  { text: 'Montserrat', flag: 'ms', value: 'ms', key: 'ms' },
  { text: 'Morocco', flag: 'ma', value: 'ma', key: 'ma' },
  { text: 'Mozambique', flag: 'mz', value: 'mz', key: 'mz' },
  { text: 'Namibia', flag: 'na', value: 'na', key: 'na' },
  { text: 'Nauru', flag: 'nr', value: 'nr', key: 'nr' },
  { text: 'Nepal', flag: 'np', value: 'np', key: 'np' },
  { text: 'Netherlands', flag: 'nl', value: 'nl', key: 'nl' },
  { text: 'Netherlandsantilles', flag: 'an', value: 'an', key: 'an' },
  { text: 'New Caledonia', flag: 'nc', value: 'nc', key: 'nc' },
  { text: 'New Guinea', flag: 'pg', value: 'pg', key: 'pg' },
  { text: 'New Zealand', flag: 'nz', value: 'nz', key: 'nz' },
  { text: 'Nicaragua', flag: 'ni', value: 'ni', key: 'ni' },
  { text: 'Niger', flag: 'ne', value: 'ne', key: 'ne' },
  { text: 'Nigeria', flag: 'ng', value: 'ng', key: 'ng' },
  { text: 'Niue', flag: 'nu', value: 'nu', key: 'nu' },
  { text: 'Norfolk Island', flag: 'nf', value: 'nf', key: 'nf' },
  { text: 'North Korea', flag: 'kp', value: 'kp', key: 'kp' },
  { text: 'Northern Mariana Islands', flag: 'mp', value: 'mp', key: 'mp' },
  { text: 'Norway', flag: 'no', value: 'no', key: 'no' },
  { text: 'Oman', flag: 'om', value: 'om', key: 'om' },
  { text: 'Pakistan', flag: 'pk', value: 'pk', key: 'pk' },
  { text: 'Palau', flag: 'pw', value: 'pw', key: 'pw' },
  { text: 'Palestine', flag: 'ps', value: 'ps', key: 'ps' },
  { text: 'Panama', flag: 'pa', value: 'pa', key: 'pa' },
  { text: 'Paraguay', flag: 'py', value: 'py', key: 'py' },
  { text: 'Peru', flag: 'pe', value: 'pe', key: 'pe' },
  { text: 'Philippines', flag: 'ph', value: 'ph', key: 'ph' },
  { text: 'Pitcairn Islands', flag: 'pn', value: 'pn', key: 'pn' },
  { text: 'Poland', flag: 'pl', value: 'pl', key: 'pl' },
  { text: 'Portugal', flag: 'pt', value: 'pt', key: 'pt' },
  { text: 'Puerto Rico', flag: 'pr', value: 'pr', key: 'pr' },
  { text: 'Qatar', flag: 'qa', value: 'qa', key: 'qa' },
  { text: 'Reunion', flag: 're', value: 're', key: 're' },
  { text: 'Romania', flag: 'ro', value: 'ro', key: 'ro' },
  { text: 'Russia', flag: 'ru', value: 'ru', key: 'ru' },
  { text: 'Rwanda', flag: 'rw', value: 'rw', key: 'rw' },
  { text: 'Saint Helena', flag: 'sh', value: 'sh', key: 'sh' },
  { text: 'Saint Kitts and Nevis', flag: 'kn', value: 'kn', key: 'kn' },
  { text: 'Saint Lucia', flag: 'lc', value: 'lc', key: 'lc' },
  { text: 'Saint Pierre', flag: 'pm', value: 'pm', key: 'pm' },
  { text: 'Saint Vincent', flag: 'vc', value: 'vc', key: 'vc' },
  { text: 'Samoa', flag: 'ws', value: 'ws', key: 'ws' },
  { text: 'San Marino', flag: 'sm', value: 'sm', key: 'sm' },
  { text: 'Sandwich Islands', flag: 'gs', value: 'gs', key: 'gs' },
  { text: 'Sao Tome', flag: 'st', value: 'st', key: 'st' },
  { text: 'Saudi Arabia', flag: 'sa', value: 'sa', key: 'sa' },
  { text: 'Scotland', flag: 'gb sct', value: 'sct', key: 'sct' },
  { text: 'Senegal', flag: 'sn', value: 'sn', key: 'sn' },
  { text: 'Serbia', flag: 'cs', value: 'cs', key: 'cs' },
  { text: 'Serbia', flag: 'rs', value: 'rs', key: 'rs' },
  { text: 'Seychelles', flag: 'sc', value: 'sc', key: 'sc' },
  { text: 'Sierra Leone', flag: 'sl', value: 'sl', key: 'sl' },
  { text: 'Singapore', flag: 'sg', value: 'sg', key: 'sg' },
  { text: 'Slovakia', flag: 'sk', value: 'sk', key: 'sk' },
  { text: 'Slovenia', flag: 'si', value: 'si', key: 'si' },
  { text: 'Solomon Islands', flag: 'sb', value: 'sb', key: 'sb' },
  { text: 'Somalia', flag: 'so', value: 'so', key: 'so' },
  { text: 'South Africa', flag: 'za', value: 'za', key: 'za' },
  { text: 'South Korea', flag: 'kr', value: 'kr', key: 'kr' },
  { text: 'Spain', flag: 'es', value: 'es', key: 'es' },
  { text: 'Sri Lanka', flag: 'lk', value: 'lk', key: 'lk' },
  { text: 'Sudan', flag: 'sd', value: 'sd', key: 'sd' },
  { text: 'Suriname', flag: 'sr', value: 'sr', key: 'sr' },
  { text: 'Swaziland', flag: 'sz', value: 'sz', key: 'sz' },
  { text: 'Sweden', flag: 'se', value: 'se', key: 'se' },
  { text: 'Switzerland', flag: 'ch', value: 'ch', key: 'ch' },
  { text: 'Syria', flag: 'sy', value: 'sy', key: 'sy' },
  { text: 'Taiwan', flag: 'tw', value: 'tw', key: 'tw' },
  { text: 'Tajikistan', flag: 'tj', value: 'tj', key: 'tj' },
  { text: 'Tanzania', flag: 'tz', value: 'tz', key: 'tz' },
  { text: 'Thailand', flag: 'th', value: 'th', key: 'th' },
  { text: 'Timorleste', flag: 'tl', value: 'tl', key: 'tl' },
  { text: 'Togo', flag: 'tg', value: 'tg', key: 'tg' },
  { text: 'Tokelau', flag: 'tk', value: 'tk', key: 'tk' },
  { text: 'Tonga', flag: 'to', value: 'to', key: 'to' },
  { text: 'Trinidad', flag: 'tt', value: 'tt', key: 'tt' },
  { text: 'Tunisia', flag: 'tn', value: 'tn', key: 'tn' },
  { text: 'Turkey', flag: 'tr', value: 'tr', key: 'tr' },
  { text: 'Turkmenistan', flag: 'tm', value: 'tm', key: 'tm' },
  { text: 'Tuvalu', flag: 'tv', value: 'tv', key: 'tv' },
  { text: 'U.A.E.', flag: 'ae', value: 'ae', key: 'ae' },
  { text: 'Uganda', flag: 'ug', value: 'ug', key: 'ug' },
  { text: 'Ukraine', flag: 'ua', value: 'ua', key: 'ua' },
  { text: 'United Kingdom', flag: 'gb', value: 'gb', key: 'gb' },
  { text: 'United States', flag: 'us', value: 'us', key: 'us' },
  { text: 'Uruguay', flag: 'uy', value: 'uy', key: 'uy' },
  { text: 'US Minor Islands', flag: 'um', value: 'um', key: 'um' },
  { text: 'US Virgin Islands', flag: 'vi', value: 'vi', key: 'vi' },
  { text: 'Uzbekistan', flag: 'uz', value: 'uz', key: 'uz' },
  { text: 'Vanuatu', flag: 'vu', value: 'vu', key: 'vu' },
  { text: 'Vatican City', flag: 'va', value: 'va', key: 'va' },
  { text: 'Venezuela', flag: 've', value: 've', key: 've' },
  { text: 'Vietnam', flag: 'vn', value: 'vn', key: 'vn' },
  { text: 'Wales', flag: 'gb wls', value: 'wls', key: 'wls' },
  { text: 'Wallis and Futuna', flag: 'wf', value: 'wf', key: 'wf' },
  { text: 'Western Sahara', flag: 'eh', value: 'eh', key: 'eh' },
  { text: 'Yemen', flag: 'ye', value: 'ye', key: 'ye' },
  { text: 'Zambia', flag: 'zm', value: 'zm', key: 'zm' },
  { text: 'Zimbabwe', flag: 'zw', value: 'zw', key: 'zw' },
];
type DropdownLanguagesComponentProps = DropdownProps & {
  languagesFilters?: string[];
};
const DropdownLanguagesComponent = (props: DropdownLanguagesComponentProps) => {
  const {
    languagesFilters = [],
    placeholder = i18n.t('dropdown_languages_placeholder_default'),
    options,
    fluid,
    search = true,
    onChange,
    ...rest
  } = props;

  const countries = useMemo(() => {
    if (options) {
      return options.filter(
        (country) => !languagesFilters.includes(country.value as string)
      );
    }
    return countryOptions.filter(
      (country) => !languagesFilters.includes(country.value as string)
    );
  }, [options, languagesFilters]);

  return (
    <Dropdown
      {...rest}
      placeholder={placeholder}
      fluid={fluid}
      selection
      search={search}
      options={countries}
      onChange={onChange}
    />
  );
};

export default DropdownLanguagesComponent;
